In [ ]:

import numpy as np #임포트 판다스를 활용하는 이유 엑셀과 연계가 쉽다.

arr = np.array([1,2,3],[4,5,6]) #array 는 다차원 배열 첫번째 행의 두번째 열은 2

print(arr)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
a = np.array([1,2,3])  #판다스에서 중요한 것은 전처리이다.
b = np.array([4,5,6])

print(a + b)

[5 7 9]

In [ ]:
# 엑셀의 데이터 중 CSV 라는 텍스트 형태의 데이터로 열어볼 수 있다. 엑셀어 없을 경우에
# PANDAS에서는 1차원을 Series 라고 부른다. 한 줄 데이터
# 2차원에서는 DataFrame 이라고 부른다. 행 + 열의 구조 ex) 엑셀의 표

pip install pandas # colab에서는 이미 설치가 되어있어서 X

SyntaxError: invalid syntax (1318965544.py, line 5)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"name": ["kim","lee","park"],"age": [25,31,28],"score" : [88,92,79]})

In [ ]:
df.shape    # (행수, 열수) <- 전체 행수와 열수를 구할 수 있다.

(3, 3)

In [ ]:
df

   name  age  score
0   kim   25     88
1   lee   31     92
2  park   28     79

In [ ]:
df.to_csv('score.csv') # 저장할때 -> 엑셀형태로

In [ ]:
# 반대로 외부의 파일을 colab으로 업로드 시킬려면 어떻게 해야하냐면 -> kaggle 에

iris_df=pd.read_csv('Iris.csv')

In [ ]:
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.shape  # iris_df 데이터프레임의 크기를 알려주는 메소드 <<<<<<데이터프레임.shape>>>>>>>>, iris_df 의 데이터프렝임의 속성은 몇개인가 = 6,>>> 속성을 물어볼때는 열을 지칭하는 것이다.(세로방향 항목의 갯수)

(150, 6)

In [ ]:
iris_df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
iris_df.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
iris_df.dtypes   #첫번째 열의 항목은(속성) = 정수, 두번째~여섯번째 열(속성) = 실수, 일곱번째 열의 속성 = 사물

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris_df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.info()   # 중요한 메소드, 데이터 프레임의 전체 정보를 알려주는 정보(info), non-null이 중요하다 누락된 값을 찾아내서 보정할 수 있따ㅑㅏ

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
iris_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
iris_df['SepalLengthCm']  # 데이터프레임에서 하나의 특정 열만 출력하고 싶을 때,  두개 이상의 열을 출력하고 싶을때는 콤마, 를 사용하여 추가 열제목을 적으면 된다.

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [ ]:
iris_df[iris_df['SepalLengthCm']>5.5]  # 조건 필터링하는 법

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.sort_values('SepalLengthCm')  #오름차순 정렬

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [ ]:
iris_df.fillna(0)  #결측치 처리

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica